# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - mock-t

on:
  push:
    branches:
      - main
    paths:
      - ./pong_backend/**
      - .github/workflows/main_transcendence-server.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: ./pong_backend
        run: npm ci

      - name: Build application
        working-directory: ./pong_backend
        run: npm run build
      - name: Create ZIP archive
        run: zip --symlinks -r nodejs-app.zip ./pong_backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: node-app.zip
        env: 
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          DEBUG: true
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'transcendence-server'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C57BBF6E64604AC4B5C070882FB6F917 }}
          package: node-app.zip
